# Generated by Django 4.0.4 on 2022-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('correo', models.CharField(max_length=55, primary_key=True, serialize=False, verbose_name='pk suscriptor')),
                ('id_suscripcion', models.IntegerField(verbose_name='id ssuscripcion')),
                ('estado', models.BooleanField(default=False, verbose_name='estado sc')),
            ],
        ),
    ]
